name: skitestore
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.4.0
  get_it: ^3.0.1
  animated_text_kit: ^1.3.1
  shared_preferences: ^0.5.3+5
  provider: ^4.0.1
  intro_slider: ^2.2.8
  fluttertoast: ^3.1.3
  flutter_spinkit: ^4.0.0
  firebase_auth: ^0.15.0+1
  google_fonts: ^0.2.0
  intro_views_flutter:
  flutter_offline: ^0.2.4
  flutter_speed_dial: ^1.2.5
  rflutter_alert: ^1.0.3
  package_info: ^0.4.0+13
  firebase_remote_config: ^0.3.0+1
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  avatar_glow:
  provider_architecture: ^1.0.5
  getflutter: ^1.0.2
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/onboard/
    - assets/image/
    - assets/watch/
    
 

 
  
  
